import {
  REQUEST_QUERY_PARAMS,
  REQUEST_STATUS,
  REQUEST_STATUS_FILTER,
  REQUEST_STATUS_FILTER_OPTIONS,
} from './request.constants';

export const ADVANCE = {
  QUERY_PARAMS: REQUEST_QUERY_PARAMS,
  STATUS: REQUEST_STATUS,
  STATUS_FILTER: REQUEST_STATUS_FILTER,
  STATUS_FILTER_OPTIONS: REQUEST_STATUS_FILTER_OPTIONS,
};
