const EXPENSE_QUERY_PARAMS = {
  STATUS: 'status',
  PAGE: 'page',
  LIMIT: 'limit',
}

const EXPENSE_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  REVIEWED: 'REVIEWED',
} as const;

const EXPENSE_STATUS_FILTER = {
  ...EXPENSE_STATUS,
  ALL: 'ALL',
} as const;

const EXPENSE_STATUS_LABEL = {
  ALL: 'All',
  PENDING: 'Pending',
  APPROVED: 'Approved',
  REJECTED: 'Rejected',
  REVIEWED: 'Reviewed',
} as const;

const EXPENSE_STATUS_FILTER_OPTIONS = [
  {
    label: EXPENSE_STATUS_LABEL.ALL,
    value: EXPENSE_STATUS_FILTER.ALL,
  },
  {
    label: EXPENSE_STATUS_LABEL.PENDING,
    value: EXPENSE_STATUS_FILTER.PENDING,
  },
  {
    label: EXPENSE_STATUS_LABEL.APPROVED,
    value: EXPENSE_STATUS_FILTER.APPROVED,
  },
  {
    label: EXPENSE_STATUS_LABEL.REJECTED,
    value: EXPENSE_STATUS_FILTER.REJECTED,
  },
  {
    label: EXPENSE_STATUS_LABEL.REVIEWED,
    value: EXPENSE_STATUS_FILTER.REVIEWED,
  },
];

export const EXPENSE = {
  QUERY_PARAMS: EXPENSE_QUERY_PARAMS,
  STATUS: EXPENSE_STATUS,
  STATUS_FILTER: EXPENSE_STATUS_FILTER,
  STATUS_FILTER_OPTIONS: EXPENSE_STATUS_FILTER_OPTIONS,
} as const;
