export const PROJECT_CONSTANTS = {
  PAGE_TITLE: 'Project Management',
  FORM_LABELS: {
    NAME: 'Project Name',
    DESCRIPTION: 'Description',
    BUDGET: 'Budget',
    START_DATE: 'Start Date',
    END_DATE: 'End Date',
    DEPARTMENT: 'Department',
  },
  TABLE_HEADERS: {
    NAME: 'Project Name',
    DESCRIPTION: 'Description',
    BUDGET: 'Budget',
    START_DATE: 'Start Date',
    END_DATE: 'End Date',
    DEPARTMENT: 'Department',
    ACTIONS: 'Actions',
  },
  ACTIONS: {
    ADD_PROJECT: 'Add Project',
    EDIT_PROJECT: 'Edit Project',
    DELETE: 'Delete',
    EDIT: 'Edit',
    CANCEL: 'Cancel',
    CREATE: 'Create Project',
    UPDATE: 'Update Project',
  },
  PLACEHOLDERS: {
    SEARCH: 'Search projects...',
    NAME: 'Enter project name',
    DESCRIPTION: 'Enter project description',
    BUDGET: 'Enter budget amount',
    START_DATE: 'Select start date',
    END_DATE: 'Select end date',
    DEPARTMENT: 'Select department',
  },
} as const;
